// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Https from "firebase-functions/https";

let Logger = {};

function raiseFirebaseHttpError(code, message, data) {
  throw new Https.HttpsError(code, message, data);
}

let HttpsError = {
  raiseFirebaseHttpError: raiseFirebaseHttpError
};

let Https$1 = {
  HttpsError: HttpsError
};

let Firestore = {};

export {
  Logger,
  Https$1 as Https,
  Firestore,
}
/* firebase-functions/https Not a pure module */
