// Generated by ReScript, PLEASE EDIT WITH CARE


let App = {};

let Timestamp = {};

let CollectionReference = {};

let QuerySnapshot = {};

let QueryDocumentSnapshot = {};

let Query = {};

let DocumentSnapshot = {};

let DocumentReference = {};

let FieldValue = {};

let Firestore = {
  Timestamp: Timestamp,
  CollectionReference: CollectionReference,
  QuerySnapshot: QuerySnapshot,
  QueryDocumentSnapshot: QueryDocumentSnapshot,
  Query: Query,
  DocumentSnapshot: DocumentSnapshot,
  DocumentReference: DocumentReference,
  FieldValue: FieldValue
};

let Auth = {};

let Storage = {};

export {
  App,
  Firestore,
  Auth,
  Storage,
}
/* No side effect */
