// Generated by ReScript, PLEASE EDIT WITH CARE


var App = {};

var CollectionReference = {};

var QuerySnapshot = {};

var QueryDocumentSnapshot = {};

var Query = {};

var DocumentSnapshot = {};

var DocumentReference = {};

var Timestamp = {};

var FieldValue = {};

var Firestore = {
  CollectionReference: CollectionReference,
  QuerySnapshot: QuerySnapshot,
  QueryDocumentSnapshot: QueryDocumentSnapshot,
  Query: Query,
  DocumentSnapshot: DocumentSnapshot,
  DocumentReference: DocumentReference,
  Timestamp: Timestamp,
  FieldValue: FieldValue
};

var Auth = {};

export {
  App ,
  Firestore ,
  Auth ,
}
/* No side effect */
