// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Https from "firebase-functions/https";

var Logger = {};

function raiseFirebaseHttpError(code, message, data) {
  throw new Https.HttpsError(code, message, data);
}

var HttpsError = {
  raiseFirebaseHttpError: raiseFirebaseHttpError
};

var Https$1 = {
  HttpsError: HttpsError
};

var Firestore = {};

export {
  Logger ,
  Https$1 as Https,
  Firestore ,
}
/* firebase-functions/https Not a pure module */
